
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.1.90:3306/blog?useSSL=false&amp;serverTimezone=Asia/Seoul
    username: maria
    password: selim0516!